
@authorization=Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJzb2Z0dGVrSldUIiwic3ViIjoianRvcnJlczk5MEBnbWFpbC5jb20iLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjA4OTk1MjM0LCJleHAiOjE2MDkwODE2MzR9.-EMy0BS-3_dGWmcM36nBIv7t_OsbjvalbnErSgIFVllNVskCLcn2CSkPSK9C8XYlg1uc61dRm-ynBupGgsMXug

###
POST http://localhost:8080/users/sign-up
Content-Type: application/x-www-form-urlencoded

{
    "firstname": "julio",
    "lastname": "torres",
    "email": "jtorres990@gmail.com",
    "phone": "3013819315",
    "password": "12345678"
}

###
POST http://localhost:8080/users/sign-up
Content-Type: application/x-www-form-urlencoded
Accept: application/json

firstname=julio&lastname=torres&email=jtorres990@gmail.com&phone=3013819315&password=12345678

###
POST http://localhost:8080/users/sign-in
Content-Type: application/x-www-form-urlencoded
Accept: application/json

email=jtorres990@gmail.com&password=12345678

###
POST http://localhost:8080/users/sign-in
Content-Type: application/json
Accept: application/json

{
    "email": "jtorres990@gmail.com",
    "password": "12345678"
}

###
GET http://localhost:8080/cities

###
GET http://localhost:8080/cities
Authorization: {{authorization}}

###
GET http://localhost:8080/people
Authorization: {{authorization}}

###
GET http://localhost:8080/people

###
PATCH http://localhost:8080/profile
Content-Type: application/json
Authorization: {{authorization}}

{
    "title": "nada",
    "description": "flojo profesional",
    "pets": "si, tengo",
    "countryOfBirth": "CO",
    "birthDate": "2020-12-26T23:55:18.198Z",
    "photoUrl": "psna",
    "countryOfResidence": "CO"
}

